apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone-app
  labels:
    app: youtube-clone-app
  namespace: youtube-cicd
spec:
  replicas: 20
  selector:
    matchLabels:
      app: youtube-clone-app
  template:
    metadata:
      labels:
        app: youtube-clone-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: youtube-clone-app
        image: harbor.y4test.local/youtube-cicd/youtube-cicd-pipeline:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
